<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="baseball.ApplicationTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2022-11-10T16:58:23" hostname="DESKTOP-C31AVHT" time="0.069">
  <properties/>
  <testcase name="예외_테스트()" classname="baseball.ApplicationTest" time="0.069">
    <failure message="java.lang.AssertionError: &#13;&#10;Expecting code to raise a throwable." type="java.lang.AssertionError">java.lang.AssertionError: 
Expecting code to raise a throwable.
	at baseball.ApplicationTest.lambda$예외_테스트$2(ApplicationTest.java:26)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:102)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <system-out><![CDATA[3개의 숫자를 모두 맞히셨습니다! 게임종료
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
